apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: web
          image: my-repo/ecommerce-app:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-credentials

